#fuzzyfinder fzf
export FZF_COMPLETION_TRIGGER='**'
#https://github.com/junegunn/fzf.vim/issues/358
export FZF_DEFAULT_OPTS="--bind ctrl-y:preview-up,ctrl-e:preview-down,ctrl-b:preview-page-up,ctrl-f:preview-page-down,ctrl-u:preview-half-page-up,ctrl-d:preview-half-page-down,shift-up:preview-top,shift-down:preview-bottom,alt-up:half-page-up,alt-down:half-page-down"
alias fzfdir="fzf --preview 'exa -l {}'"

alias .="source"
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias ......="cd ../../../../.."
alias .......="cd ../../../../../.."
alias ........="cd ../../../../../../.."
alias .........="cd ../../../../../../../.."
alias ..........="cd ../../../../../../../../.."
alias ...........="cd ../../../../../../../../../.."
alias zz="cd -"
alias fuck="thefuck"
alias bat="batcat"
alias fz="fzf --preview 'batcat --color=always --style=header,grid --line-range :500 {}'"
alias s="sudo"
alias c="clear"
alias l="exa -l"
alias ll="exa -l -a"
alias la="exa -la"
alias lt="exa -T"
alias llt="exa -lT"
alias lla="exa -laT"
#use fdfind instead of find (alias fd)
alias fd="fdfind"
alias f="fd"
alias v="vim"
alias b="bat"
alias t="tmux"
alias g="git"
alias h="history"
alias p="python"
alias w="wget"
alias r="ranger"
alias e="exit"
alias m="make"
alias t="tree"
alias u="uptime"
alias i="ip"
alias j="journalctl"
alias k="kill"
alias y="yes"
alias x="exit"
alias q="exit"

alias dl="cd /root/downloads"

alias metz="cd /var/www/html/metz"
alias up="metz && cd wp-content/uploads"
alias pl="metz && cd wp-content/plugins"
alias th="metz && cd wp-content/themes"
